/* ===== SAMPLE DATA FOR SCREENSHOTS ===== */

/* Context (adjust names if needed) */
USE ROLE CHINOOK_ROLE;
USE WAREHOUSE CHINOOK_WH;
USE DATABASE CHINOOK_DB;

/* Ensure schemas exist */
CREATE SCHEMA IF NOT EXISTS CHINOOK_DB.STAGE;
CREATE SCHEMA IF NOT EXISTS CHINOOK_DB.DW;

/* ---------- 1) Seed STAGE with small random-ish data ---------- */
-- Clean current stage rows so screenshots match exactly
TRUNCATE TABLE IF EXISTS CHINOOK_DB.STAGE.ARTIST;
TRUNCATE TABLE IF EXISTS CHINOOK_DB.STAGE.GENRE;
TRUNCATE TABLE IF EXISTS CHINOOK_DB.STAGE.ALBUM;
TRUNCATE TABLE IF EXISTS CHINOOK_DB.STAGE.CUSTOMER;
TRUNCATE TABLE IF EXISTS CHINOOK_DB.STAGE.INVOICE;
TRUNCATE TABLE IF EXISTS CHINOOK_DB.STAGE.INVOICELINE;

-- ARTIST
INSERT INTO CHINOOK_DB.STAGE.ARTIST (ARTISTID, NAME, CREATED_BY, CREATED_DT) VALUES
  (1,'Neon Echo','seed', '2024-01-02'),
  (2,'Lo-Fi Waves','seed', '2024-01-02'),
  (3,'Quantum Strings','seed', '2024-01-02');

-- GENRE (not used in current loads, fine for screenshots)
INSERT INTO CHINOOK_DB.STAGE.GENRE (GENREID, NAME, CREATED_BY, CREATED_DT) VALUES
  (1,'Electronic','seed','2024-01-02'),
  (2,'Indie','seed','2024-01-02');

-- ALBUM
INSERT INTO CHINOOK_DB.STAGE.ALBUM (ALBUMID, TITLE, ARTISTID, CREATED_BY, CREATED_DT) VALUES
  (10,'Midnight Drive',1,'seed','2024-01-03'),
  (11,'Coffee & Code',2,'seed','2024-01-03'),
  (12,'Superposition',3,'seed','2024-01-03');

-- CUSTOMER
INSERT INTO CHINOOK_DB.STAGE.CUSTOMER
(CUSTOMERID,FIRSTNAME,LASTNAME,COMPANY,ADDRESS,CITY,STATE,COUNTRY,POSTALCODE,PHONE,FAX,EMAIL,SUPPORTREPID,CREATED_BY,CREATED_DT)
VALUES
  (101,'Ava','Patel','Skyline Data','11 Harbor St','Boston','MA','USA','02115','617-555-0101',NULL,'ava.patel@example.com', 5,'seed','2024-01-05'),
  (102,'Liam','Nguyen','Northwind Labs','55 Cedar Ave','Seattle','WA','USA','98101','206-555-0102',NULL,'liam.nguyen@example.com', 7,'seed','2024-01-05'),
  (103,'Mia','Garcia',NULL,'901 Oak Rd','Austin','TX','USA','73301','512-555-0103',NULL,'mia.garcia@example.com', 9,'seed','2024-01-05');

-- INVOICE (fact uses Invoice.Total and InvoiceDate -> DATE_DIM_KEY)
INSERT INTO CHINOOK_DB.STAGE.INVOICE
(INVOICEID, CUSTOMERID, INVOICEDATE, BILLINGADDRESS, BILLINGCITY, BILLINGSTATE, BILLINGCOUNTRY, BILLINGPOSTALCODE, TOTAL, CREATED_BY, CREATED_DT)
VALUES
  (10001,101,'2024-02-14 10:35:00','11 Harbor St','Boston','MA','USA','02115', 59.98,'seed','2024-02-14'),
  (10002,102,'2024-03-01 16:20:00','55 Cedar Ave','Seattle','WA','USA','98101', 29.99,'seed','2024-03-01'),
  (10003,101,'2024-03-15 09:05:00','11 Harbor St','Boston','MA','USA','02115', 89.50,'seed','2024-03-15'),
  (10004,103,'2025-01-10 13:42:00','901 Oak Rd','Austin','TX','USA','73301', 15.00,'seed','2025-01-10');

-- INVOICELINE (not needed for fact insert here, but handy for screenshots)
INSERT INTO CHINOOK_DB.STAGE.INVOICELINE
(INVOICELINEID, INVOICEID, TRACKID, UNITPRICE, QUANTITY, CREATED_BY, CREATED_DT)
VALUES
  (1,10001,501,29.99,2,'seed','2024-02-14'),
  (2,10002,601,29.99,1,'seed','2024-03-01'),
  (3,10003,701,44.75,2,'seed','2024-03-15'),
  (4,10004,801, 7.50,2,'seed','2025-01-10');

/* ---------- 2) Make sure calendar dims exist/populated ---------- */
-- DATE_DIM (simple wide range; idempotent)
INSERT INTO CHINOOK_DB.DW.DATE_DIM (
  DATE_KEY, FULL_DATE, DAY_NUM, WEEKDAY_ABBR, WEEKDAY_NUM,
  DAY_OF_YEAR_NUM, WEEK_OF_YEAR, MONTH_NUM, MONTH_ABBR,
  QUARTER_NUM, QUARTER_NAME, YEAR_NUM, FIRST_DAY_OF_MONTH,
  LAST_DAY_OF_MONTH, IS_WEEKEND
)
WITH seq AS (
  SELECT DATEADD(day, ROW_NUMBER() OVER (ORDER BY SEQ4()) - 1, '2024-01-01'::DATE) AS d
  FROM TABLE(GENERATOR(ROWCOUNT => 800))  -- ~2.2 years
)
SELECT
  TO_NUMBER(TO_CHAR(d,'YYYYMMDD')) AS DATE_KEY,
  d AS FULL_DATE,
  EXTRACT(DAY FROM d),
  UPPER(TO_CHAR(d,'DY')),
  EXTRACT(DOW FROM d),
  EXTRACT(DOY FROM d),
  TO_NUMBER(TO_CHAR(d,'IW')),
  EXTRACT(MONTH FROM d),
  UPPER(TO_CHAR(d,'MON')),
  EXTRACT(QUARTER FROM d),
  CONCAT('Q', EXTRACT(QUARTER FROM d)),
  EXTRACT(YEAR FROM d),
  DATE_TRUNC('MONTH', d),
  LAST_DAY(d),
  IFF(EXTRACT(DOW FROM d) IN (0,6), 'Y','N')
FROM seq
QUALIFY NOT EXISTS (
  SELECT 1 FROM CHINOOK_DB.DW.DATE_DIM t
  WHERE t.DATE_KEY = TO_NUMBER(TO_CHAR(d,'YYYYMMDD'))
);

-- TIME_DIM (HH:MM; idempotent)
INSERT INTO CHINOOK_DB.DW.TIME_DIM (TIME_KEY, HOUR_NUM, MINUTE_NUM, TIME_24_HR)
WITH h AS (SELECT SEQ4() AS h FROM TABLE(GENERATOR(ROWCOUNT => 24))),
     m AS (SELECT SEQ4() AS m FROM TABLE(GENERATOR(ROWCOUNT => 60)))
SELECT
  (h.h*100 + m.m),
  h.h,
  m.m,
  LPAD(h.h::STRING,2,'0') || ':' || LPAD(m.m::STRING,2,'0')
FROM h CROSS JOIN m
QUALIFY NOT EXISTS (
  SELECT 1 FROM CHINOOK_DB.DW.TIME_DIM t
  WHERE t.TIME_KEY = (h.h*100 + m.m)
);

/* ---------- 3) Helper views (for MERGE + Fact) ---------- */
CREATE OR REPLACE VIEW CHINOOK_DB.STAGE.VW_CUSTOMER_WITH_HASH AS
SELECT
  c.CUSTOMERID,
  c.FIRSTNAME, c.LASTNAME, c.COMPANY, c.CITY, c.STATE, c.COUNTRY, c.POSTALCODE,
  c.SUPPORTREPID,
  SHA2(
    CONCAT_WS('|',
      NVL(TRIM(c.FIRSTNAME),''),
      NVL(TRIM(c.LASTNAME),''),
      NVL(TRIM(c.COMPANY),''),
      NVL(TRIM(c.CITY),''),
      NVL(TRIM(c.STATE),''),
      NVL(TRIM(c.COUNTRY),''),
      NVL(TRIM(c.POSTALCODE),''),
      NVL(TO_VARCHAR(c.SUPPORTREPID),'')
    ), 256
  ) AS CUSTOMER_HASH_VAL
FROM CHINOOK_DB.STAGE.CUSTOMER c;

CREATE OR REPLACE VIEW CHINOOK_DB.STAGE.VW_INVOICE_KEYS AS
SELECT
  i.INVOICEID,
  i.CUSTOMERID,
  TO_DATE(i.INVOICEDATE) AS INVOICEDT,
  TO_NUMBER(TO_CHAR(TO_DATE(i.INVOICEDATE),'YYYYMMDD')) AS DATE_KEY,
  i.TOTAL
FROM CHINOOK_DB.STAGE.INVOICE i;

/* ---------- 4) Load DIMs (MERGE) ---------- */
MERGE INTO CHINOOK_DB.DW.CUSTOMER_DIM d
USING CHINOOK_DB.STAGE.VW_CUSTOMER_WITH_HASH s
  ON d.CUSTOMER_ID = s.CUSTOMERID
WHEN NOT MATCHED THEN
  INSERT (CUSTOMER_KEY, CUSTOMER_ID, FIRST_NAME, LAST_NAME, COMPANY_NAME, CITY, STATE, COUNTRY, ZIP_CODE,
          EMPLOYEE_ID, IS_ACTIVE, SOURCE_ID, DATE_TO_WAREHOUSE, CUSTOMER_HASH_VAL)
  VALUES (CHINOOK_DB.DW.CUSTOMER_DIM_SEQ.NEXTVAL, s.CUSTOMERID, s.FIRSTNAME, s.LASTNAME, s.COMPANY, s.CITY, s.STATE,
          s.COUNTRY, s.POSTALCODE, s.SUPPORTREPID, 'Y', 'SQLSERVER_CHINOOK', CURRENT_TIMESTAMP(), s.CUSTOMER_HASH_VAL)
WHEN MATCHED AND NVL(d.CUSTOMER_HASH_VAL,'') <> NVL(s.CUSTOMER_HASH_VAL,'') THEN
  UPDATE SET
    d.FIRST_NAME        = s.FIRSTNAME,
    d.LAST_NAME         = s.LASTNAME,
    d.COMPANY_NAME      = s.COMPANY,
    d.CITY              = s.CITY,
    d.STATE             = s.STATE,
    d.COUNTRY           = s.COUNTRY,
    d.ZIP_CODE          = s.POSTALCODE,
    d.EMPLOYEE_ID       = s.SUPPORTREPID,
    d.SOURCE_ID         = 'SQLSERVER_CHINOOK',
    d.DATE_TO_WAREHOUSE = CURRENT_TIMESTAMP(),
    d.CUSTOMER_HASH_VAL = s.CUSTOMER_HASH_VAL;

MERGE INTO CHINOOK_DB.DW.ARTIST_DIM d
USING (SELECT ARTISTID, NAME AS ARTISTNAME FROM CHINOOK_DB.STAGE.ARTIST) s
  ON d.ARTIST_ID = s.ARTISTID
WHEN NOT MATCHED THEN
  INSERT (ARTIST_KEY, ARTIST_ID, ARTIST_NAME, SOURCE_ID, DATE_TO_WAREHOUSE)
  VALUES (CHINOOK_DB.DW.ARTIST_DIM_SEQ.NEXTVAL, s.ARTISTID, s.ARTISTNAME, 'SQLSERVER_CHINOOK', CURRENT_TIMESTAMP())
WHEN MATCHED AND NVL(d.ARTIST_NAME,'') <> NVL(s.ARTISTNAME,'') THEN
  UPDATE SET
    d.ARTIST_NAME       = s.ARTISTNAME,
    d.SOURCE_ID         = 'SQLSERVER_CHINOOK',
    d.DATE_TO_WAREHOUSE = CURRENT_TIMESTAMP();

/* ---------- 5) Load FACT ---------- */
INSERT INTO CHINOOK_DB.DW.SALES_FACT
  (SALES_KEY, CUSTOMER_KEY, INVOICE_ID, DATE_DIM_KEY, TOTAL_SALE_AMT, SOURCE_ID, DATE_TO_WAREHOUSE)
SELECT
  CHINOOK_DB.DW.SALES_FACT_SEQ.NEXTVAL,
  cd.CUSTOMER_KEY,
  k.INVOICEID,
  dd.DATE_KEY,
  k.TOTAL,
  k.INVOICEID,
  CURRENT_TIMESTAMP()
FROM CHINOOK_DB.STAGE.VW_INVOICE_KEYS k
JOIN CHINOOK_DB.DW.DATE_DIM dd
  ON dd.DATE_KEY = k.DATE_KEY
JOIN CHINOOK_DB.DW.CUSTOMER_DIM cd
  ON cd.CUSTOMER_ID = k.CUSTOMERID
WHERE NOT EXISTS (
  SELECT 1 FROM CHINOOK_DB.DW.SALES_FACT f WHERE f.INVOICE_ID = k.INVOICEID
);

/* ---------- 6) Screenshot-friendly outputs ---------- */
-- Quick counts
SELECT 'DATE_DIM' AS TABLE_NAME, COUNT(*) AS ROWS FROM CHINOOK_DB.DW.DATE_DIM
UNION ALL SELECT 'TIME_DIM', COUNT(*) FROM CHINOOK_DB.DW.TIME_DIM
UNION ALL SELECT 'CUSTOMER_DIM', COUNT(*) FROM CHINOOK_DB.DW.CUSTOMER_DIM
UNION ALL SELECT 'ARTIST_DIM', COUNT(*) FROM CHINOOK_DB.DW.ARTIST_DIM
UNION ALL SELECT 'SALES_FACT', COUNT(*) FROM CHINOOK_DB.DW.SALES_FACT;

-- A few dimension rows
SELECT CUSTOMER_KEY, CUSTOMER_ID, FIRST_NAME, LAST_NAME, CITY, STATE, COUNTRY
FROM CHINOOK_DB.DW.CUSTOMER_DIM
ORDER BY CUSTOMER_ID
LIMIT 10;

SELECT ARTIST_KEY, ARTIST_ID, ARTIST_NAME
FROM CHINOOK_DB.DW.ARTIST_DIM
ORDER BY ARTIST_ID
LIMIT 10;

-- Fact joined to date & customer
SELECT f.INVOICE_ID, f.TOTAL_SALE_AMT, d.FULL_DATE, c.FIRST_NAME, c.LAST_NAME, c.CITY, c.STATE
FROM CHINOOK_DB.DW.SALES_FACT f
JOIN CHINOOK_DB.DW.DATE_DIM d ON d.DATE_KEY = f.DATE_DIM_KEY
JOIN CHINOOK_DB.DW.CUSTOMER_DIM c ON c.CUSTOMER_KEY = f.CUSTOMER_KEY
ORDER BY f.INVOICE_ID;
